version: '3'

services:
  elasticsearch:
    image: elasticsearch:2.4.6-alpine
    # image: elasticsearch:5.6.10

    volumes:
      - ./locales/data:/usr/share/elasticsearch/data:rw
      - ./locales/run.sh:/dev_stack/locales/run.sh
    ports:
      - "9200:9200"
      - "9300:9300"
    command: "/dev_stack/locales/run.sh"

  db:
    image: mysql:5.5
    container_name: seafile-mysql
    volumes:
      - ./localdb/data:/var/lib/mysql:rw
      - ./localdb/run.sh:/dev_stack/localdb/run.sh
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    command: "/dev_stack/localdb/run.sh"

  memcached:
    image: memcached:1.4-alpine
    container_name: seafile-memcached
    ports:
      - "11211:11211"

  nginx:
    image: "nginx"
    container_name: seafile-nginx
    restart: always
    volumes:
      - ./localnginx/conf.d:/etc/nginx/conf.d
      - media_volume:/code/seahub/media
      - static_volume:/code/seahub/static
    ports:
      - "80:80"

  pro:
    # image: xiez/seafile-dev-pro:6.3.5-pro
    image: xiez/seafile-dev-pro:docs-6.3.2

    environment:
      - DOCKER_DEV=1
      - LOCAL_USER_ID=1000
      - IS_PRO_VERSION=1
      - LICENSE_DIR=/code/seaf-license # comment this value if image is pro:6.0
      - CCNET_CONF_DIR=/code/seafile-pro-server/tests/conf
      - SEAFILE_CONF_DIR=/code/seafile-pro-server/tests/conf/seafile-data
      - EVENTS_CONFIG_FILE=/code/seafevents/events.conf
      - PYTHONPATH=/code:/code/seafevents:/usr/local/lib/python2.7/dist-packages:/code/seahub/thirdpart:/code/seahub-extra
      - PYTHON_EGG_CACHE=/tmp
      - MIGRATE_SEAHUB_DB=0
      - DJANGO_SETTINGS_MODULE=seahub.settings
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LC_LANG=en_US.UTF-8
      

    container_name: seafile-dev-pro

    volumes:
      - /Users/xiez/dev/seaf-license:/code/seaf-license
      - ./seafile-mysql-conf:/code/seafile-pro-server/tests/conf
      - media_volume:/code/seahub/media
      - static_volume:/code/seahub/static
      - ./seahub-data/avatars:/code/seahub/media/avatars
      - ./seahub-data/thumbnail/thumb:/code/seahub/seahub/thumbnail/thumb

      # - /Users/xiez/dev/seahub:/code/seahub
      # - /Users/xiez/dev/seahub-extra/seahub_extra:/code/seahub_extra
      # - /Users/xiez/dev/seafevents:/code/seafevents
      # - /Users/xiez/dev/seafes:/code/seafes
      # - /Users/xiez/dev/seafobj/seafobj:/code/seafobj

    ports:
     - "8000:8000"
     - "8082:8082"
     - "3000:3000"
    depends_on:
      - db
      - memcached
      - nginx
    command: ./start-services.sh

# networks:
#   nginx_network:
#     driver: bridge

volumes:
  media_volume:
  static_volume: